name: Deploy Backend to Vercel

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'agent/**'
      - '.github/workflows/vercel-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps (sanity check)
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Install Vercel CLI
        run: npm i -g vercel@latest
      - name: Deploy to Vercel
        working-directory: backend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID
          vercel deploy --prod --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID --yes

